src/SalesBundle/Form/CartType.php
<?php

namespace SalesBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CartType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('createdAt')
            ->add('modifiedAt')
            ->add('paymentMethod')
            ->add('status')
            ->add('message')
            ->add('user')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SalesBundle\Entity\Cart'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'salesbundle_cart';
    }
}

src/SalesBundle/Controller/CartController.php
<?php

namespace SalesBundle\Controller;

use MyWedding\ProduitBundle\Entity\Product;
use MyWedding\UserBundle\Entity\User;
use DateTime;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use SalesBundle\Entity\Cart;
use SalesBundle\Entity\CartItem;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\JsonResponse;

class CartController extends Controller
{
    /**
     * Displays "Shopping Cart" page.
     *
     * @return RedirectResponse|Response
     */
    public function indexAction(Request $request)
    {
        $user = $this->getUser();
        if ($user)
        {
            $em = $this->getDoctrine()->getManager();
            $cart = $em->getRepository('SalesBundle:Cart')->findOneBy(
                ['user' => $user, 'status' => Cart::STATUS_PROCESSING]
            );
            $items = null;
            $total = 0;
            if ($cart != null) {
                $items = $cart->getItems();
                $total = self::calculateTotalPrice($items);
            }
            return $this->render(
                'SalesBundle:Default:cart/index.html.twig',
                [
                    'items' => $items,
                    'total' => $total,
                ]
            );
        }else{
            $products = $request->getSession()->get('products');
            return $this->render(
                'SalesBundle:Default:cart/index.html.twig',[
                    'products' => $products,
                    'items' => 0,
                    'total' => 0,
                ]
            );
        }


    }

    public function indexAdminAction()
    {
        $user = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $carts = $em->getRepository('SalesBundle:Cart')->findListCartAdmin();
        //$cart = $em->getRepository('SalesBundle:Cart')->findOneBy(['user' => $user, 'status' => Cart::STATUS_PROCESSING]);
        /*$items = null;
        $total = 0;
        if ($carts != null) {
            $items = $carts->getItems();
            $total = self::calculateTotalPrice($items);
        }*/

        return $this->render(
            'SalesBundle:Default:cart/indexAdmin.html.twig',
            [
                'carts' => $carts,
            ]
        );
    }

    /**
     * Updates shopping cart.
     *
     * @param Request $request
     *
     * @return RedirectResponse
     */
    public function updateAction(Request $request)
    {
        $items = $request->get('item');
        $em = $this->getDoctrine()->getManager();
        foreach ($items as $id => $qty) {
            $cartItem = $em->getRepository('SalesBundle:CartItem')->find($id);
            if (intval($qty) > 0) {
                $cartItem->setQty($qty);
                $em->persist($cartItem);
            } else {
                $em->remove($cartItem);
            }
        }
        $em->flush();
        $this->addFlash('success', 'Cart updated.');

        return $this->redirectToRoute('web_shop_sales_cart');
    }

    /**
     * Adds products to shopping cart.
     *
     * @param int $id
     *
     * @return RedirectResponse
     */
    public function addAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $product = $em->getRepository('MyWeddingProduitBundle:Product')->find($id);
        if ($user = $this->getUser()) {
            /**
             * @var $product Product
             * @var $user User
             * @var $em EntityManager
             */
            $now = new DateTime;
            $cart = $em->getRepository('SalesBundle:Cart')->findOneBy(
                ['user' => $user, 'status' => Cart::STATUS_PROCESSING]
            );
            $cart = $this->persistCart($user, $now, $em, $cart, Cart::STATUS_PROCESSING);
            $em->flush();
            $cartItem = $em->getRepository('SalesBundle:CartItem')->findOneBy(['cart' => $cart, 'product' => $product]);
            $this->persistCartItem($now, $cart, $product, $em, $cartItem);
            $em->flush();

//            $this->addFlash('success', sprintf('%s successfully added to cart', $product->getName()));

            return $this->redirectToRoute('web_shop_sales_cart');
        } else {
            $session = $request->getSession();
            if ($session->has('products')) {
                $products = $session->get('products');
                array_push($products,$product);
                $session->set('products', $products);
            } //if it doesnt create the session and push a array for testing
            else {
                $products = [];
                array_push($products, $product);
                $session->set('products', $products);
            }
            $referer = $request->headers->get('referer');
            return new RedirectResponse($referer);
        }
    }

    /**
     * Calculates total price.
     *
     * @param CartItem[] $items
     *
     * @return float
     */
    public static function calculateTotalPrice($items)
    {
        $total = null;
        foreach ($items as $item) {
            $total += floatval($item->getQty() * $item->getUnitPrice());
        }

        return $total;
    }

    /**
     * Creates the cart for current user.
     *
     * @param User $user
     * @param DateTime $now
     * @param EntityManager $em
     * @param Cart $cart
     *
     * @return Cart
     */
    private function persistCart(User $user, DateTime $now, EntityManager $em, Cart $cart = null, $status)
    {
        if (!$cart) {
            $cart = new Cart;
            $cart->setUser($user);
            $cart->setCreatedAt($now);
            $cart->setModifiedAt($now);
            $cart->setStatus($status);
        } else {
            $cart->setModifiedAt($now);
        }
        $em->persist($cart);

        return $cart;
    }

    /**
     * Creates the chosen cart item.
     *
     * @param DateTime $now
     * @param Cart $cart
     * @param Product $product
     * @param EntityManager $em
     * @param CartItem $cartItem
     */
    private function persistCartItem(
        DateTime $now,
        Cart $cart,
        Product $product,
        EntityManager $em,
        CartItem $cartItem = null
    ) {
        if (!$cartItem) {
            $cartItem = new CartItem;
            $cartItem->setCart($cart);
            $cartItem->setProduct($product);
            $cartItem->setQty(1);
            if ($product->getPromotion() == false) {
                $cartItem->setUnitPrice($product->getPrix());
            } else {
                $cartItem->setUnitPrice(
                    $product->getPrix() - (($product->getPrix() * $product->getPromotion()->getPercent()) / 100)
                );
            }
            $cartItem->setCreatedAt($now);
            $cartItem->setModifiedAt($now);
        } else {
            $cartItem->setQty($cartItem->getQty() + 1);
            $cartItem->setModifiedAt($now);
        }
        $em->persist($cartItem);
    }

    public function removeItemFromCartAction($idItem)
    {
        $em = $this->getDoctrine()->getManager();
        $cartItem = $em->getRepository('SalesBundle:CartItem')->find($idItem);
        $em->remove($cartItem);
        $em->flush();

        return $this->redirectToRoute('web_shop_sales_cart');
    }


    public function removeItemFromCartAjaxAction(Request $req)
    {
        $em = $this->getDoctrine()->getManager();
        $idItem = $req->get('idItem');
        $cartItem = $em->getRepository('SalesBundle:CartItem')->find($idItem);
        if($cartItem != null) {
            $em->remove($cartItem);
            $em->flush();
        }

        return new JsonResponse(array('data', 1));
    }

    public function editStatusAction($id, $status)
    {

        $em = $this->getDoctrine()->getManager();

        $cart = $em->getRepository('SalesBundle:Cart')->find($id);
        if($cart != null){
            $cart->setStatus($status);
            $em->flush();
        }

        return $this->redirectToRoute('my_Wedding_commande');
    }

    public function showDetailCartAdminAction($id)
    {

        $em = $this->getDoctrine()->getManager();

        $cart = $em->getRepository('SalesBundle:Cart')->find($id);

        return $this->render(
            'SalesBundle:Default:cart/detailCmdAdmin.html.twig',
            [
                'cart' => $cart,
            ]
        );
    }

    public function editStatusUserAction($id)
    {

        $em = $this->getDoctrine()->getManager();

        $cart = $em->getRepository('SalesBundle:Cart')->find($id);
        if($cart != null){
            $cart->setStatus(Cart::STATUS_CANCELED);
            $em->flush();
        }

        return $this->redirectToRoute('user_prof');
    }


}

src/SalesBundle/Controller/DefaultController.php
<?php

namespace SalesBundle\Controller;

use SalesBundle\Entity\Cart;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\BrowserKit\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('SalesBundle:Default:index.html.twig');
    }

// n5arjou les details
    public function ordersAction(Request $request)
    {
        $user = $this->getUser();
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }

        $em = $this->getDoctrine()->getManager();
        $cart = $em->getRepository('SalesBundle:Cart')->findBy(['user' => $user]);

        $total[]=array();
        foreach ($cart as $c){
            $items = $c->getItems();
            $cartSubtotal = CartController::calculateTotalPrice($items);
            $total[] = $cartSubtotal;
        }
        return $this->render('SalesBundle:Default/checkout:orders.html.twig', [
            'customer_orders' => $cart,
            'total'=>$total
        ]);
    }
// koll commande mnech metkawna
    public function detailOrderAction($idCmd){
        $user = $this->getUser();
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }

        $em = $this->getDoctrine()->getManager();
        $cart = $em->getRepository('SalesBundle:CartItem')->findBy(['cart'=>$idCmd]);

         $total = 0;
        foreach ($cart as $item) {
            $total = $total + $item->getUnitPrice()*$item->getQty();
        }

        return $this->render('SalesBundle:Default/checkout:detailOrders.html.twig', [
            'cart' => $cart, 'total'=>$total
        ]);
    }
}

src/SalesBundle/Resources/views/Default/cart/cartIcone.html.twig
<a href="#" data-toggle="modal" data-target="#cart"><img src="{{ asset('images/Cart.svg') }}"></a>
{% set p = app.session.has('products') %}
{% if app.user or p == null %}
    <div id="cart" class="cart modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="title">
                        <img src="{{ asset('images/Cart.svg') }}">
                        <h5 class="upper"><span class="nb-item">{{ nbrItems }}</span> Articles</h5>
                    </div>

                    <div class="titles">
                        <div class="col-md-6">Article</div>
                        <div class="col-md-2">Prix Unitaire</div>
                        <div class="col-md-2">Quantité</div>
                        <div class="col-md-2">Prix Total</div>
                    </div>

                    {% for key,item in items  %}
                        <div class="cart-item">
                            <div class="col-md-6 article">
                                <div class="image">
                                    <img src="{{ asset('upload/img/'~item.product.pictures[0].id~'.'~item.product.pictures[0].path) }}"
                                         alt=""/>
                                </div>
                            </div>
                            <div class="col-md-2 unit-price">
                                <span>{{ item.product.prix }} </span><span>DT</span>
                            </div>
                            <div class="col-md-2 quantity">
                                <i class="material-icons minus">remove</i>
                                <span id="qty{{ item.id }}">{{ item.qty }}</span>
                                <i class="material-icons plus">add</i>
                            </div>
                            <div class="col-md-2 total-price">
                                {% set price =  item.product.prix * item.qty %}
                                <span>{{ price }} </span><span>DT</span>
                            </div>
                            <button>
                                <i class="material-icons delete"><a onclick="deletee{{ item.id }}()">clear</a></i>
                            </button>
                        </div>
                        <script>
                            function deletee{{ item.id }}() {
                                $('#valider-le-panier').toggleClass('disabled');
                                $.ajax({
                                    url : '{{ path('web_shop_sales_cart_remove', { 'idItem': item.id }) }}', // La ressource ciblée
                                    type : 'POST', // Le type de la requête HTTP.
                                    success: function (data, status, object) {
                                        $('#valider-le-panier').toggleClass('disabled');
                                    }

                                })

                            }
                        </script>
                        <script>
                            jQuery(document).on('DOMSubtreeModified', '#qty{{ item.id }}', function () {
                                qty = document.getElementById('qty{{ item.id }}').innerHTML;
                                $('#valider-le-panier').toggleClass('disabled');
                                $.ajax({
                                    url : '{{ path('cart_item_change_qty',{id:item.id}) }}', // La ressource ciblée
                                    type : 'POST', // Le type de la requête HTTP.
                                    data : 'quantite=' + qty,
                                    success: function (data, status, object) {
                                        $('#valider-le-panier').toggleClass('disabled');
                                    }

                                })});

                        </script>
                    {% endfor %}
                    <div class="choice">
                        <div class="col-md-6">
                            <button class="flat-btn rippler"><i class="material-icons">keyboard_backspace</i>continuer
                                la navigation
                            </button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ path('web_shop_sales_cart') }}" id="valider-le-panier" class="btn flat-btn">Valider le panier</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div id="cart" class="cart modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="title">
                        <img src="{{ asset('images/Cart.svg') }}">
                        {% if products %}
                            <h5 class="upper"><span class="nb-item">{{ products|length }}</span> Articles</h5>
                        {% endif %}
                    </div>

                    <div class="titles">
                        <div class="col-md-6">Article</div>
                        <div class="col-md-2">Prix Unitaire</div>
                    </div>

                    {% for product in products if products %}
                        <div class="cart-item">
                            <div class="col-md-6 article">
                                <span style="">{{ product.name }} </span>
                            </div>
                            <div class="col-md-2 unit-price" style="padding-top: 0px !important;">
                                <span>{{ product.prix }} </span><span>DT</span>
                            </div>
                            <button>
                                <i class="material-icons delete">clear</i>
                            </button>
                        </div>
                    {% endfor %}
                    <div class="choice">
                        <div class="col-md-6">
                            <button class="flat-btn rippler"><i class="material-icons">keyboard_backspace</i>continuer
                                la navigation
                            </button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ path('my_wedding_produit_homepage_signup') }}" class="btn flat-btn">Valider le
                                panier</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endif %}

src/SalesBundle/Resources/views/Default/cart/detailCmdAdmin.html.twig
{% extends "layoutAdmin.html.twig" %}
 {% block breadcrumb %}
     <div class="row">
         <ol class="breadcrumb">
             <li><a href="{{ path('my_Wedding_stat') }}">
                     <svg class="glyph stroked home">
                         <use xlink:href="#stroked-home"></use>
                     </svg>
                 </a></li>
             <li class="active">Détail commande </li>
         </ol>
     </div><!--/.row-->
 {% endblock %}
{% block body -%}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                   <strong>Commande N° :</strong>  {{ cart.id }}
                    <table data-toggle="table" data-show-columns="true" data-search="true"
                           data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name"
                           data-sort-order="desc">
                        <thead>
                        <tr>
                            <th data-sortable="true">Nom produit</th>
                            <th data-sortable="true">Qte</th>
                            <th data-sortable="true">Prix unitaire</th>
                            <th data-sortable="true">Prix total</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% set total = 0 %}
                        {% for entity in cart.items %}
                            <tr>
                                <td>{{ entity.product.name }}</td>
                                <td>{{ entity.qty }}</td>
                                <td>
                                   {{ entity.unitPrice }}
                                </td>
                                <td>{% set total = total +(entity.unitPrice * entity.qty) %}{{ entity.unitPrice * entity.qty }}DT</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <strong>Total de la commande:</strong>  {{ total }}DT
                </div>
            </div>
        </div>
    </div><!--/.row-->

{% endblock %}

src/SalesBundle/Resources/views/Default/cart/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Cart edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('cart') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/SalesBundle/Resources/views/Default/cart/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}


    <!--PAYMENT START-->

    <section class="order" id="order">
        <div class="container">

            <!--BREADCRUMB START-->

            <div class="breadcrumb">
                <ul>
                    <li><a href="#">Accueil</a></li>
                    <li><a href="paiement.html">Panier</a></li>
                </ul>
            </div>

            <!--BREADCRUMB END-->

            <!--ORDER GRID START-->

            <div class="ias-spinner-products"></div>
            <div class="col-md-8">
                <div class="card" style="padding: 20px !important;">

                    <div class="">

                        <div class="slide shipment active">
                            {% if items|length >0 %}
                                <form action="{{ path('web_shop_sales_cart_update') }}" id="update-form" method="post">
                                    <div class="shopping-cart outer-top-small">
                                        <div class="shopping-cart-table ">
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                    <tr>
                                                        <th class="cart-description item">Image</th>
                                                        <th class="cart-qty item">Quantité</th>
                                                        <th class="cart-sub-total item">Prix</th>
                                                        <th class="cart-total last-item">Prix total</th>
                                                        <th class="cart-romove item">Supprimer</th>

                                                    </tr>
                                                    </thead>
                                                    <!-- /thead -->

                                                    <tbody>
                                                    {% for item in items %}
                                                        <tr>

                                                            <td class="cart-image">
                                                                <a class="entry-thumbnail"
                                                                   href="#">
                                                                    <img style="height: 100px"
                                                                         src="{{ asset('upload/img/'~item.product.pictures[0].id~'.'~item.product.pictures[0].path) }}"
                                                                         alt=""/>
                                                                </a>
                                                            </td>

                                                            <td class="cart-product-quantity">
                                                                <div class="quant-input">
                                                                    <!--<div class="arrows">
                                                                        <div class="arrow plus gradient"><span class="ir"><i class="icon fa fa-sort-asc"></i></span></div>
                                                                        <div class="arrow minus gradient"><span class="ir"><i class="icon fa fa-sort-desc"></i></span></div>
                                                                    </div>-->
                                                                    <input type="number" onchange="sendUpdateForm()" name="item[{{ item.id }}]"
                                                                           value="{{ item.qty }}"
                                                                           min="1" max="{{ item.product.stock }}">
                                                                </div>
                                                            </td>
                                                            <td class="cart-product-sub-total"><span
                                                                        class="cart-sub-total-price">{{ item.unitPrice }}
                                                                    DT</span></td>
                                                            <td class="cart-product-grand-total"><span
                                                                        class="cart-grand-total-price">{{ item.qty * item.unitPrice }}
                                                                    DT</span>
                                                            </td>
                                                            <td class="romove-item"><a
                                                                        href="{{ path('web_shop_sales_cart_remove', {'idItem' : item.id}) }}"
                                                                        title="cancel" class="icon"><i
                                                                            class="fa fa-trash-o"></i></a></td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                                <!-- /table -->
                                            </div>

                                        </div>

                                    </div>
                                    <div class="shopping-cart-btn mag-top-40">

                                    </div>
                                    <!-- /.shopping-cart-btn -->
                                    <!-- /.shopping-cart -->
                                </form>
                            {% else %}

                                <div class="row ">
                                    <div class="" style="margin: 10px;">
                                        <strong>Information!</strong> Votre panier est vide.
                                    </div>
                                </div>
                            {% endif %}
                        </div>


                    </div>
                    {#<button class="flat-btn rippler prev-btn">Précedent</button>
                    <button class="flat-btn rippler next-btn">Suivant</button>#}
                </div>
            </div>

            <div class="col-md-4">
                <div class="summary card">
                    <h5>récapitulatif</h5>

                    <div class="total-article">
                        Total Articles<span>{{ total }}<span> DT</span></span>
                    </div>
                    <div class="shipping-fees">
                        Frais de livraison<span>Gratuit</span>
                    </div>
                    <div class="total">
                        Total<span>{{ total }}<span> DT</span></span>
                    </div>
                    <ul class="nav nav-pills nav-stacked left-menu" id="stacked-menu">
                        <li>
                            <p><a href="#" class="promotion collapsing-btn collapsed" data-target="#item1"
                                  data-toggle="collapse" data-parent="#stacked-menu">Code promotionnel ?<i
                                            class="material-icons">chevron_right</i></a></p>
                            <ul class="nav nav-stacked collapse left-submenu" id="item1">
                                <li>
                                    <div class="text-field">
                                        <label for="" class="text-field-label">Code Promotionnel</label>
                                        <input type="text" name="promotion-code" class="text-field-input">
                                    </div>
                                </li>
                            </ul>

                        </li>
                    </ul>

                    <a class="button" onclick="sendUpdateForm()" href="{{ path('web_shop_sales_checkout') }}">Passer la commande</a>

                    <button type="submit" onclick="document.getElementById('update-form').submit();"
                            class="flat-btn">Mise à jour mon panier
                    </button>
                    <a class="button rippler" href="{{ path('my_wedding_produit_homepage') }}">
                        Retour a la boutique
                    </a>

                </div>
            </div>

            <!--ORDER GRID END-->

            <!--SUMMARY SIDEBAR START-->

            <!--SUMMARY SIDEBAR END-->

        </div>
    </section>

    <!--PAYMENT END-->

{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script>
        function sendUpdateForm() {

            $.ajax({
                type: $('#update-form').attr('method'),
                url: '{{ path('web_shop_sales_cart_update') }}',
                data: $('#update-form').serialize(),
                dataType: "html",
                success: function (data, status, object) {
                   document.location.href = '{{ path('web_shop_sales_checkout') }}' ;

                },
                error: function (data, status, object) {
                }
            });
        }

    </script>
{% endblock %}